# Use root/example as user/password credentials
# version: '3.1'

# services:
#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_USER: arden
#       MYSQL_PASSWORD: password
#       MYSQL_DATABASE: employee-management


version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'employee-management'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: